INSERT INTO public.events (
  title,
  slug,
  city_name,
  venue_name,
  venue_address,
  event_type,
  status,
  starts_at,
  ends_at,
  capacity,
  price_cents,
  currency,
  invite_requirement,
  visibility,
  featured,
  short_description,
  full_description,
  guest_list_status,
  video_required,
  verification_required,
  access_mode,
  pairing_preferences_status,
  updated_at
)
VALUES
  (
    'FaceMeet Dallas Social',
    'facemeet-dallas-social-2026-07-16',
    'Dallas, TX',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-07-16 19:00:00-05',
    '2026-07-16 22:00:00-05',
    NULL,
    0,
    'USD',
    'approval_required',
    'featured',
    TRUE,
    'A curated FaceMeet social for Dallas members ready to meet beyond the screen.',
    'FaceMeet Dallas Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet Austin Social',
    'facemeet-austin-social-2026-08-05',
    'Austin, TX',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-08-05 19:00:00-05',
    '2026-08-05 22:00:00-05',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for Austin members ready to meet beyond the screen.',
    'FaceMeet Austin Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet Houston Social',
    'facemeet-houston-social-2026-08-20',
    'Houston, TX',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-08-20 19:00:00-05',
    '2026-08-20 22:00:00-05',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for Houston members ready to meet beyond the screen.',
    'FaceMeet Houston Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet Atlanta Social',
    'facemeet-atlanta-social-2026-09-05',
    'Atlanta, GA',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-09-05 19:00:00-04',
    '2026-09-05 22:00:00-04',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for Atlanta members ready to meet beyond the screen.',
    'FaceMeet Atlanta Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet Miami Social',
    'facemeet-miami-social-2026-09-20',
    'Miami, FL',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-09-20 19:00:00-04',
    '2026-09-20 22:00:00-04',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for Miami members ready to meet beyond the screen.',
    'FaceMeet Miami Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet New York Social',
    'facemeet-new-york-social-2026-10-05',
    'New York, NY',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-10-05 19:00:00-04',
    '2026-10-05 22:00:00-04',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for New York members ready to meet beyond the screen.',
    'FaceMeet New York Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet Los Angeles Social',
    'facemeet-los-angeles-social-2026-10-20',
    'Los Angeles, CA',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-10-20 19:00:00-07',
    '2026-10-20 22:00:00-07',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for Los Angeles members ready to meet beyond the screen.',
    'FaceMeet Los Angeles Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet Chicago Social',
    'facemeet-chicago-social-2026-11-05',
    'Chicago, IL',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-11-05 19:00:00-06',
    '2026-11-05 22:00:00-06',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for Chicago members ready to meet beyond the screen.',
    'FaceMeet Chicago Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet Washington DC Social',
    'facemeet-washington-dc-social-2026-11-20',
    'Washington, DC',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-11-20 19:00:00-05',
    '2026-11-20 22:00:00-05',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for Washington DC members ready to meet beyond the screen.',
    'FaceMeet Washington DC Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet San Francisco Social',
    'facemeet-san-francisco-social-2026-12-05',
    'San Francisco, CA',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-12-05 19:00:00-08',
    '2026-12-05 22:00:00-08',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for San Francisco members ready to meet beyond the screen.',
    'FaceMeet San Francisco Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  ),
  (
    'FaceMeet Lagos Social',
    'facemeet-lagos-social-2026-12-20',
    'Lagos, Nigeria',
    'Venue to be announced',
    'Venue to be announced',
    'social',
    'published',
    '2026-12-20 19:00:00+01',
    '2026-12-20 22:00:00+01',
    NULL,
    0,
    'USD',
    'approval_required',
    'public',
    FALSE,
    'A curated FaceMeet social for Lagos members ready to meet beyond the screen.',
    'FaceMeet Lagos Social is an approval-required in-person social experience for FaceMeet members.',
    'open',
    TRUE,
    FALSE,
    'individual_request',
    'closed',
    now()
  )
ON CONFLICT (slug) DO UPDATE
SET
  title = EXCLUDED.title,
  city_name = EXCLUDED.city_name,
  venue_name = EXCLUDED.venue_name,
  venue_address = EXCLUDED.venue_address,
  event_type = EXCLUDED.event_type,
  status = EXCLUDED.status,
  starts_at = EXCLUDED.starts_at,
  ends_at = EXCLUDED.ends_at,
  capacity = EXCLUDED.capacity,
  price_cents = EXCLUDED.price_cents,
  currency = EXCLUDED.currency,
  invite_requirement = EXCLUDED.invite_requirement,
  visibility = EXCLUDED.visibility,
  featured = EXCLUDED.featured,
  short_description = EXCLUDED.short_description,
  full_description = EXCLUDED.full_description,
  guest_list_status = EXCLUDED.guest_list_status,
  video_required = EXCLUDED.video_required,
  verification_required = EXCLUDED.verification_required,
  access_mode = EXCLUDED.access_mode,
  pairing_preferences_status = EXCLUDED.pairing_preferences_status,
  updated_at = now();
